// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVFz1dR-xGSR2FzgAnF7pqEmxxE3HuGtQ',
    appId: '1:618461569072:android:0c00bff31a7d04184d8df5',
    messagingSenderId: '618461569072',
    projectId: 'familytreeapp-6bb53',
    databaseURL: 'https://familytreeapp-6bb53-default-rtdb.firebaseio.com',
    storageBucket: 'familytreeapp-6bb53.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIHOBYNI1PqSM-fy9EH2YbVo16yek686M',
    appId: '1:618461569072:ios:ded37b1b9841208d4d8df5',
    messagingSenderId: '618461569072',
    projectId: 'familytreeapp-6bb53',
    databaseURL: 'https://familytreeapp-6bb53-default-rtdb.firebaseio.com',
    storageBucket: 'familytreeapp-6bb53.appspot.com',
    iosBundleId: 'com.example.familyTree',
  );

}